### ISSUE TITLE
Compatibility with Angular 12.x /  RxJS 6.x

### ISSUE THREAD

**Issue by ctaepper** [mrahhal/ngx-chain-guards#1]
this is great, I had the same concept in mind, but found out you already took a stab at it. I would love to use that for our project, we are in a routing config hell because we heavily use guards to ensure data loading and so on.

You have one single peer dependency to @angular/router@13. This is acutally not necessary. it works the same way with angular 12. The only problem that I am having is https://github.com/mrahhal/ngx-chain-guards/blob/main/packages/ngx-chain-guards/src/chain.ts#L41 where you use an observable from RxJS 7. 

Could you provide a version that runs with RxJS 6? basically replacing `firstValueFrom` with the RxJS 6 equivalent?

**Comment by ctaepper** [comment]
btw: this should really come out of the box from Angular - no idea why they have that not built in....

**Comment by mrahhal** [comment]
Would have done that if the changes were only code. I made this target v13 to spare the headache of dealing with (and maintaining) versions before 13 (since 13 introduced package format changes). I would have to release a separate package only to target v12. I don't have the free time to do that right now, so I'd recommend just copying the code if you can't update angular to 13 in your project. If you face any code problems with it I can help. (instead of `firstValueFrom` you can probably use `result.first().toPromise()` in rxjs 6, that should be the only needed change)

> btw: this should really come out of the box from Angular - no idea why they have that not built in....

Agreed.

**Comment by ctaepper** [comment]
yes I agree this 12->13 is a mess. I will copy the code and make some changes. so thanks for the "blueprint"

**Comment by mrahhal** [comment]
No worries, let me know if you face problems.
